#!/usr/bin/env bash
# Drives run-openhands.sh into every verdict it can reach and pins which one
# wins when several are true at once.
#
# This is not a test of exit statuses. Nothing in this project reads them: a
# human reads the message after an unattended run, at a site that is reachable
# about once a month, and acts on it. So the assertions below are as much about
# what each verdict must NOT say as about what it must -- "raise the cap
# deliberately" printed for a run that errored on every turn asks the operator
# to spend more money on a configuration that cannot work, and it is a month
# before they find out.
#
# The harness is stubbed rather than run. Every condition here -- a stream that
# stops dead, a process killed by the wall clock, a CLI that exits 0 having
# emitted nothing -- is trivial to produce from a stub and awkward, slow or
# impossible to produce reliably from the real CLI against a real endpoint.
# tests/integration/openhands-wire.sh covers the real thing; this covers the
# decision.
set -uo pipefail
# Fatal: every path below is repo-relative.
cd "$(dirname "$0")/.." || { echo "${0##*/}: cannot reach the repository root" >&2; exit 1; }
# shellcheck source=tests/lib/assert.sh
. tests/lib/assert.sh

# The adapter reads the event kind with jq, so without it every line parses as
# no kind at all and the ConversationErrorEvent branch silently never fires --
# which is to say the test would pass while measuring nothing. One clear skip,
# as elsewhere in this suite; CI runs on a host that has jq.
for tool in jq timeout mkfifo; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    printf 'SKIP %s: no %s, and the adapter needs it to reach any verdict\n' \
      "${0##*/}" "$tool"
    exit 0
  fi
done

# The method here is a stub the adapter execs off PATH, and the build host --
# the machine that most needs to run this, because it is the one with the
# container engine -- runs fapolicyd, which refuses to execute anything under
# /tmp, /var/tmp or /dev/shm. Skipping there would retire the test on the only
# machine that can also run the integration suite, so the scratch parent is
# probed instead of assumed. A noexec mount fails identically and is handled by
# the same probe.
scratch_parent() {
  local d f
  for d in "${TMPDIR:-/tmp}" "$HOME" "$PWD"; do
    if [ -z "$d" ] || [ ! -d "$d" ] || [ ! -w "$d" ]; then continue; fi
    f="$d/.cranopener-exec-probe.$$"
    printf '#!/bin/sh\nexit 0\n' >"$f" 2>/dev/null || continue
    chmod +x "$f" 2>/dev/null || { rm -f "$f"; continue; }
    if "$f" 2>/dev/null; then rm -f "$f"; printf '%s\n' "$d"; return 0; fi
    rm -f "$f"
  done
  return 1
}

PARENT="$(scratch_parent)" || {
  printf 'SKIP %s: nothing writable here permits execution (fapolicyd? noexec?),\n' "${0##*/}"
  printf '     and this test works by putting a stub harness on PATH\n'
  exit 0
}

WORK="$(mktemp -d -p "$PARENT")"
trap 'rm -rf "$WORK"' EXIT

BIN="$WORK/bin"
mkdir -p "$BIN" "$WORK/persist" "$WORK/ws"

# Stands in for the OpenHands CLI. The adapter finds it with `command -v
# openhands`, so putting it first on PATH is the whole of the injection.
#
# `exec sleep` rather than `sleep`: the adapter's `timeout` signals its direct
# child only, and a shell that stayed alive holding the FIFO open would leave
# the reader blocked on a stream nobody is going to close. exec makes the
# sleeping process the one holding the write end.
cat >"$BIN/openhands" <<'STUB'
#!/usr/bin/env bash
set -u
if [ -n "${FAKE_OH_EMIT:-}" ] && [ -f "$FAKE_OH_EMIT" ]; then
  cat "$FAKE_OH_EMIT"
fi
if [ -n "${FAKE_OH_SLEEP:-}" ]; then
  exec sleep "$FAKE_OH_SLEEP"
fi
exit "${FAKE_OH_RC:-0}"
STUB

# The adapter validates the settings file through this before launching
# anything. The file itself is generated by the real SDK and is not what is
# under test here, so the interpreter is stubbed to agree and the settings file
# is supplied via CRANOPENER_OPENHANDS_KEEP_SETTINGS.
cat >"$BIN/stub-python" <<'STUB'
#!/usr/bin/env bash
exit 0
STUB

chmod +x "$BIN/openhands" "$BIN/stub-python"
printf '{}\n' >"$WORK/persist/agent_settings.json"

# Six events, no errors: an ordinary healthy run. Kinds are the ones the SDK
# actually emits; only ConversationErrorEvent changes the verdict, but a stream
# of one repeated kind would not exercise the counting.
cat >"$WORK/events-clean.jsonl" <<'EOF'
{"kind":"MessageEvent"}
{"kind":"ActionEvent"}
{"kind":"ObservationEvent"}
{"kind":"ActionEvent"}
{"kind":"ObservationEvent"}
{"kind":"MessageEvent"}
EOF

# The error arrives as event two, so a cap of two makes both conditions true on
# the same event -- which is the case the ordering exists for.
cat >"$WORK/events-error.jsonl" <<'EOF'
{"kind":"MessageEvent"}
{"kind":"ConversationErrorEvent","code":"BadRequestError","detail":"this endpoint does not support the 'tools' parameter"}
{"kind":"MessageEvent"}
{"kind":"ActionEvent"}
EOF

: >"$WORK/events-none.jsonl"

BASE='http://127.0.0.1:9/v1'
LOG="$WORK/log"
RC=0

drive() {
  # usage: drive <max-iterations> <timeout-seconds> <emit-file> <sleep> <rc>
  # Leaves the merged output in $LOG and the adapter's status in $RC.
  local max="$1" secs="$2" emit="$3" nap="$4" rc="$5"
  PATH="$BIN:$PATH" \
  FAKE_OH_EMIT="$emit" FAKE_OH_SLEEP="$nap" FAKE_OH_RC="$rc" \
  CRANOPENER_OPENHANDS_KEEP_SETTINGS=1 \
  CRANOPENER_OPENHANDS_PYTHON="$BIN/stub-python" \
  CRANOPENER_OPENHANDS_GENERATOR="$BIN/stub-python" \
  OPENHANDS_PERSISTENCE_DIR="$WORK/persist" \
  OPENHANDS_WORK_DIR="$WORK/ws" \
  CRANOPENER_MAX_ITERATIONS="$max" \
  CRANOPENER_TIMEOUT_SECONDS="$secs" \
  CRANOPENER_LLM_BASE_URL="$BASE" \
    bash scripts/run-openhands.sh openai/provider-a/fake 'the task' >"$LOG" 2>&1
  RC=$?
}

says()      { grep -q -- "$1" "$LOG"; }
never_says() { ! grep -q -- "$1" "$LOG"; }

show() {
  # The verdict as the operator sees it. Printed for every case, passing or
  # not: the value of this file is that a reader can check the wording without
  # running anything, and a test that only prints on failure cannot offer that.
  printf -- '--- %s -> exit %d ---\n' "$1" "$RC"
  sed -n '/^run-openhands.sh:/,$p' "$LOG" | sed 's/^/    /'
  printf '\n'
}

# --- errors alone ----------------------------------------------------------
drive 50 60 "$WORK/events-error.jsonl" '' 0
show 'errors, cap not reached'
assert_eq 'an errored run exits 4' '4' "$RC"
assert_ok 'it names the conversation errors' says '1 conversation error(s)'
assert_ok 'it prints the error code and detail' \
  says 'code=BadRequestError'
assert_ok 'it does not invent a cap that was never reached' \
  never_says 'iteration cap'

# --- errors AND the cap ----------------------------------------------------
# The case the ordering exists for. Both conditions are true; the operator must
# be told about the errors, because the instruction the cap carries -- raise it,
# or shorten the task -- is the most expensive wrong answer available here.
drive 2 60 "$WORK/events-error.jsonl" '' 0
show 'errors AND the iteration cap'
assert_eq 'a run that errored and hit the cap is a failed run, exit 4' '4' "$RC"
assert_ok 'the errors are the headline' says '1 conversation error(s)'
assert_ok 'the cap survives as context' \
  says 'also stopped at the iteration cap'
assert_ok 'it does NOT tell the operator to raise the cap' \
  never_says 'Raise the cap deliberately'

# --- the cap alone ---------------------------------------------------------
drive 3 60 "$WORK/events-clean.jsonl" '' 0
show 'the iteration cap, no errors'
assert_eq 'a capped run exits 5' '5' "$RC"
assert_ok 'it says the cap stopped it' \
  says 'stopped at the iteration cap, with no conversation errors'
assert_ok 'and only then offers to raise it' says 'Raise the cap deliberately'
assert_ok 'it does not claim a conversation error' \
  never_says 'conversation error(s);'

# --- the wall clock, with nothing emitted ----------------------------------
# A harness that blackholes: a dropped proxy connection, a DNS timeout on the
# LLM path. Zero events AND a timeout are both true, and the zero-events
# diagnosis would send the next visit to the model prefix and the base URL,
# neither of which is wrong with it.
drive 50 1 "$WORK/events-none.jsonl" 10 0
show 'the wall clock, nothing emitted'
assert_eq 'a timed-out run exits 5' '5' "$RC"
assert_ok 'a timeout is reported as a timeout' \
  says 'stopped at the wall-clock bound'
assert_ok 'the silence is reported as context' \
  says 'emitted nothing at all before the bound fired'
assert_ok 'it does not send the reader to the model prefix' \
  never_says 'Check the model prefix'

# --- the wall clock, with events -------------------------------------------
drive 50 2 "$WORK/events-clean.jsonl" 10 0
show 'the wall clock, after events'
assert_eq 'a timed-out run with events also exits 5' '5' "$RC"
assert_ok 'it is still reported as the wall clock' \
  says 'stopped at the wall-clock bound'
assert_ok 'it does not claim the iteration cap' never_says 'iteration cap'

# --- a harness that failed and said so, having emitted nothing -------------
# A CLI that died in startup emits no events either. Its own status and stderr
# are the lead; the model prefix is not.
drive 50 60 "$WORK/events-none.jsonl" '' 3
show 'harness exited 3, nothing emitted'
assert_eq "the harness's own status is forwarded" '3' "$RC"
assert_ok 'it reports what the harness did' \
  says 'harness exited 3 after 0 stream events'
assert_ok 'it does not send the reader to the model prefix' \
  never_says 'Check the model prefix'

# --- zero events from a clean exit -----------------------------------------
# Trap 1 in the shape it takes: an unresolvable model prefix makes litellm give
# up before opening a socket and the CLI exits 0 having sent nothing.
drive 50 60 "$WORK/events-none.jsonl" '' 0
show 'zero events, harness exited 0'
assert_eq 'a silent clean exit is a failed run, exit 4' '4' "$RC"
assert_ok 'it says the harness exited 0 having emitted nothing' \
  says 'exited 0 having emitted no events at all'
assert_ok 'it names the two things worth checking' says 'Check the model prefix'
assert_ok 'it does not claim a timeout' never_says 'wall-clock bound'

# --- the run that worked ---------------------------------------------------
drive 50 60 "$WORK/events-clean.jsonl" '' 0
show 'a healthy run'
assert_eq 'a healthy run exits 0' '0' "$RC"
assert_ok 'it reports the counts it saw' \
  says 'completed: 6 stream events, 2 agent action(s)'

finish
