"""Generate the OpenHands CLI's ``agent_settings.json``.

The CLI does not read a hand-written config file. ``AgentStore.load_from_disk``
does ``Agent.model_validate_json(...)`` on the file, and ``AgentStore.save``
writes it with ``agent.model_dump_json(context={"expose_secrets": True})``
(see ``openhands_cli/stores/agent_store.py``). The file is therefore a
serialized pydantic model of ``openhands.sdk.Agent``, complete with the
discriminator keys the SDK adds for its polymorphic fields. A hand-written
approximation fails validation, and ``load_from_disk`` swallows that failure --
it prints one line and returns ``None``, after which the CLI silently builds a
default agent. So the file must be generated by constructing a real ``Agent``
with the installed SDK, which is what this script does.

The only setting that matters for a provider whose endpoint refuses the
``tools`` parameter is ``native_tool_calling=False``. That puts the SDK into
prompt-mode tool calling, where tool definitions are rendered into the system
prompt and no ``tools`` key is sent on the wire.

``--model`` must carry a prefix litellm recognises as a provider, e.g.
``openai/<name>``, not the vendor's own name. litellm resolves the transport
from that prefix; an unrecognised one makes it give up before opening a socket,
and the CLI reports no error and exits 0, so the run looks like a success that
simply had nothing to say. With ``openai/`` the ``--base-url`` decides where the
request actually goes, which is the whole point.

Deliberately has no ``#!`` line: build hosts running fapolicyd refuse to read
shebang'd Python files, and this is always invoked as ``python3 <file>``. It
must run with the interpreter that has ``openhands`` installed.

Two modes:

  write   --model/--base-url/--api-key[-env]/--out, generating the file
  check   --check PATH, loading an existing file through the same
          ``Agent.model_validate_json`` the CLI uses and asserting
          ``native_tool_calling``

The check mode exists because generation is not the only way this file can be
wrong. It can be stale from a previous model, hand-edited, truncated by a full
disk, or mounted from somewhere else entirely -- and every one of those
degrades the same silent way, into a default agent that sends ``tools``. The
adapter runs the check immediately before launching the harness, so what is
asserted is the file the harness is about to read, not the file this script
once wrote.

Usage:
  python3 make-openhands-settings.py --model openai/some-model \
      --base-url https://endpoint.example/v1 --api-key-env CRANOPENER_LLM_API_KEY \
      --out "$OPENHANDS_PERSISTENCE_DIR/agent_settings.json"

  python3 make-openhands-settings.py --check "$OPENHANDS_PERSISTENCE_DIR/agent_settings.json"
"""
import argparse
import os
import sys

from openhands.sdk import LLM, Agent


def build_agent(model, base_url, api_key, native_tool_calling):
    llm = LLM(
        model=model,
        base_url=base_url,
        api_key=api_key,
        native_tool_calling=native_tool_calling,
        usage_id="agent",
    )
    # No condenser and no critic: both would carry a second LLM whose own
    # native_tool_calling default is True, and the CLI applies env overrides to
    # the condenser LLM as well. Leaving them unset keeps exactly one LLM in
    # the file. The CLI fills tools, mcp_config and agent_context in at runtime
    # regardless of what is stored, so they are left at their defaults here.
    return Agent(llm=llm)


def check(path, native_tool_calling):
    """Load `path` the way the CLI does and assert native_tool_calling.

    Deliberately the same call as ``AgentStore.load_from_disk`` --
    ``Agent.model_validate_json`` -- because the failure being caught is that
    the store swallows a validation error, prints one line, returns None, and
    lets the CLI build a default agent whose ``native_tool_calling`` is True.
    Anything short of actually validating the bytes would miss it.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            payload = fh.read()
        agent = Agent.model_validate_json(payload)
    except OSError as exc:
        # Message rather than traceback: the reader's next move is to look at
        # the path, and thirty lines of pydantic frames do not help them get
        # there any faster.
        raise SystemExit("%s: cannot read: %s" % (path, exc))
    except ValueError as exc:
        raise SystemExit(
            "%s: does not load as an openhands.sdk.Agent, so the CLI would "
            "discard it and silently run a default agent with "
            "native_tool_calling=True: %s" % (path, str(exc).splitlines()[0]))

    if agent.llm.native_tool_calling != native_tool_calling:
        raise SystemExit(
            "%s: native_tool_calling=%r, wanted %r. Running as-is sends a "
            "`tools` array to an endpoint that discards it without complaining, "
            "so the run does not fail -- it just never calls a tool."
            % (path, agent.llm.native_tool_calling, native_tool_calling))

    print("checked %s (native_tool_calling=%r)"
          % (path, agent.llm.native_tool_calling), file=sys.stderr)
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--model")
    p.add_argument("--base-url")
    p.add_argument("--api-key",
                   help="the key itself; prefer --api-key-env")
    # /proc/<pid>/cmdline is world-readable on Linux and /proc/<pid>/environ is
    # not, so a key passed as an argument is legible to every other uid on the
    # box for the lifetime of the call, and lands in `ps` output besides. The
    # variable name is what crosses the command line here; the value never
    # does.
    p.add_argument("--api-key-env", metavar="VAR",
                   help="name of an environment variable holding the key")
    p.add_argument("--out")
    p.add_argument("--check", metavar="PATH",
                   help="validate an existing settings file instead of "
                        "writing one, and exit non-zero if it would not load "
                        "or carries the wrong native_tool_calling")
    p.add_argument("--native-tool-calling", action="store_true",
                   help="leave native tool calling on (the SDK default); "
                        "omit this for prompt-mode tool calling")
    args = p.parse_args(argv)

    if args.check:
        return check(args.check, args.native_tool_calling)

    missing = [name for name, value in (("--model", args.model),
                                        ("--base-url", args.base_url),
                                        ("--out", args.out)) if not value]
    if missing:
        p.error("missing required argument(s): %s" % ", ".join(missing))

    if bool(args.api_key) == bool(args.api_key_env):
        p.error("give exactly one of --api-key or --api-key-env")

    if args.api_key_env:
        api_key = os.environ.get(args.api_key_env)
        # An unset variable would otherwise serialize as the string "None" and
        # authenticate against nothing, which the provider reports as a 401 the
        # operator then debugs at the gateway instead of here.
        if not api_key:
            raise SystemExit(
                "$%s is unset or empty, so there is no API key to write into "
                "%s" % (args.api_key_env, args.out))
    else:
        api_key = args.api_key

    agent = build_agent(args.model, args.base_url, api_key,
                        args.native_tool_calling)
    # The same call AgentStore.save makes. Without the context the api_key
    # serializes as '**********' and the stored file cannot authenticate.
    payload = agent.model_dump_json(context={"expose_secrets": True})

    # Round-trip before writing. load_from_disk swallows a validation failure --
    # it prints one line, returns None, and the CLI builds a default agent whose
    # native_tool_calling is True, which sends `tools` and gets every request
    # rejected. That degradation is silent and the CLI still exits 0, so the
    # only cheap place to catch it is here, against the same call the store
    # makes. A generator that cannot prove its own output loads is worth little.
    reloaded = Agent.model_validate_json(payload)
    if reloaded.llm.native_tool_calling != args.native_tool_calling:
        raise SystemExit(
            "refusing to write %s: it round-trips with native_tool_calling=%r, "
            "wanted %r. The SDK's serialization has moved; do not ship this."
            % (args.out, reloaded.llm.native_tool_calling,
               args.native_tool_calling))

    out = os.path.abspath(args.out)
    parent = os.path.dirname(out)
    if parent and not os.path.isdir(parent):
        # 0700 only on a directory this script creates. Tightening one that
        # already exists is not ours to do and fails outright on a shared
        # parent like /tmp, taking the whole generation with it. The 0600 on
        # the file below is what actually protects the key.
        os.makedirs(parent, mode=0o700, exist_ok=True)
    # The payload carries the API key in the clear -- that is what
    # `expose_secrets` above is for -- so the file must not exist, at any
    # instant, with any byte of it in it, readable by another uid.
    #
    # `open(out, "w")` creates at the process umask, 0022 on a stock image, and
    # narrowing it afterwards leaves the key world-readable for the length of
    # the write plus the chmod. Worse, a chmod that never runs -- an exception
    # in between, a full disk, a SIGTERM -- leaves it that way permanently, and
    # nothing downstream would ever notice. The module already declines to put
    # the key on /proc/<pid>/cmdline; leaving it in a 0644 file is the same
    # exposure with a longer lifetime.
    #
    # The fchmod is not redundant with O_CREAT's mode. O_CREAT ignores the mode
    # argument entirely when the file already exists, which is the ordinary
    # case here -- this is regenerated on every run -- so on the second run
    # O_CREAT would do nothing and a pre-existing 0644 file would keep its
    # mode. fchmod is what narrows it, and it runs after O_TRUNC has emptied
    # the file and before the first byte of the payload is written: at every
    # instant the file has contents, it is 0600.
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.fchmod(fd, 0o600)
        fh = os.fdopen(fd, "w", encoding="utf-8")
    except BaseException:
        # Only reached while `fd` is still the only reference to the
        # descriptor. Once fdopen has taken it, the `with` below owns it and
        # closing here as well would close a descriptor something else may have
        # been handed in the meantime.
        os.close(fd)
        raise
    with fh:
        fh.write(payload)
    print("wrote %s (%d bytes, native_tool_calling=%r)"
          % (out, len(payload), reloaded.llm.native_tool_calling),
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
