"""Generate the OpenHands CLI's ``agent_settings.json``.

The CLI does not read a hand-written config file. ``AgentStore.load_from_disk``
does ``Agent.model_validate_json(...)`` on the file, and ``AgentStore.save``
writes it with ``agent.model_dump_json(context={"expose_secrets": True})``
(see ``openhands_cli/stores/agent_store.py``). The file is therefore a
serialized pydantic model of ``openhands.sdk.Agent``, complete with the
discriminator keys the SDK adds for its polymorphic fields. A hand-written
approximation fails validation, and ``load_from_disk`` swallows that failure --
it prints one line and returns ``None``, after which the CLI silently builds a
default agent. So the file must be generated by constructing a real ``Agent``
with the installed SDK, which is what this script does.

The only setting that matters for a provider whose endpoint refuses the
``tools`` parameter is ``native_tool_calling=False``. That puts the SDK into
prompt-mode tool calling, where tool definitions are rendered into the system
prompt and no ``tools`` key is sent on the wire.

``--model`` must carry a prefix litellm recognises as a provider, e.g.
``openai/<name>``, not the vendor's own name. litellm resolves the transport
from that prefix; an unrecognised one makes it give up before opening a socket,
and the CLI reports no error and exits 0, so the run looks like a success that
simply had nothing to say. With ``openai/`` the ``--base-url`` decides where the
request actually goes, which is the whole point.

Deliberately has no ``#!`` line: build hosts running fapolicyd refuse to read
shebang'd Python files, and this is always invoked as ``python3 <file>``. It
must run with the interpreter that has ``openhands`` installed.

Usage:
  python3 make-openhands-settings.py --model openai/some-model \
      --base-url https://endpoint.example/v1 --api-key KEY \
      --out "$OPENHANDS_PERSISTENCE_DIR/agent_settings.json"
"""
import argparse
import os
import sys

from openhands.sdk import LLM, Agent


def build_agent(model, base_url, api_key, native_tool_calling):
    llm = LLM(
        model=model,
        base_url=base_url,
        api_key=api_key,
        native_tool_calling=native_tool_calling,
        usage_id="agent",
    )
    # No condenser and no critic: both would carry a second LLM whose own
    # native_tool_calling default is True, and the CLI applies env overrides to
    # the condenser LLM as well. Leaving them unset keeps exactly one LLM in
    # the file. The CLI fills tools, mcp_config and agent_context in at runtime
    # regardless of what is stored, so they are left at their defaults here.
    return Agent(llm=llm)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--model", required=True)
    p.add_argument("--base-url", required=True)
    p.add_argument("--api-key", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--native-tool-calling", action="store_true",
                   help="leave native tool calling on (the SDK default); "
                        "omit this for prompt-mode tool calling")
    args = p.parse_args(argv)

    agent = build_agent(args.model, args.base_url, args.api_key,
                        args.native_tool_calling)
    # The same call AgentStore.save makes. Without the context the api_key
    # serializes as '**********' and the stored file cannot authenticate.
    payload = agent.model_dump_json(context={"expose_secrets": True})

    # Round-trip before writing. load_from_disk swallows a validation failure --
    # it prints one line, returns None, and the CLI builds a default agent whose
    # native_tool_calling is True, which sends `tools` and gets every request
    # rejected. That degradation is silent and the CLI still exits 0, so the
    # only cheap place to catch it is here, against the same call the store
    # makes. A generator that cannot prove its own output loads is worth little.
    reloaded = Agent.model_validate_json(payload)
    if reloaded.llm.native_tool_calling != args.native_tool_calling:
        raise SystemExit(
            "refusing to write %s: it round-trips with native_tool_calling=%r, "
            "wanted %r. The SDK's serialization has moved; do not ship this."
            % (args.out, reloaded.llm.native_tool_calling,
               args.native_tool_calling))

    out = os.path.abspath(args.out)
    parent = os.path.dirname(out)
    if parent and not os.path.isdir(parent):
        # 0700 only on a directory this script creates. Tightening one that
        # already exists is not ours to do and fails outright on a shared
        # parent like /tmp, taking the whole generation with it. The 0600 on
        # the file below is what actually protects the key.
        os.makedirs(parent, mode=0o700, exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(payload)
    os.chmod(out, 0o600)
    print("wrote %s (%d bytes, native_tool_calling=%r)"
          % (out, len(payload), reloaded.llm.native_tool_calling),
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
